### ISSUE TITLE
使用Docker编译错误，无法获取python:3.7-centos7

### ISSUE THREAD

**Issue by Hodoio** [lewangdev/PaddleWebOCR#13]
Sending build context to Docker daemon  24.53MB
Step 1/17 : FROM nodejs as nodejsbuilder
 ---> 353fd9e69501
Step 2/17 : FROM gcc:8.2.0-centos7 as gccbuilder
 ---> 9d2833aebadd
**Step 3/17 : FROM python:3.7-centos7
manifest for python:3.7-centos7 not found: manifest unknown: manifest unknown**

**Comment by lewangdev** [comment]
python:3.7-centos7 也需要自己创建，可能创建这个 image 的过程失败，那么需要自行参考项目里面的 Dockerfile 来构建：

```
sudo docker build . -f Dockerfile-python-3.7-centos7 -t python:3.7-centos7
```

项目里面的 Image 都是通过源代码构建的，所以随着时间的推移和开源软件的更新，可能会构建失败。
