### ISSUE TITLE
pip 安装依赖提示 Microsoft Visual C++ 14.0 or greater is required

### ISSUE THREAD

**Issue by test-black** [lewangdev/PaddleWebOCR#8]
错误日志：[error.log](https://github.com/lewangdev/PaddleWebOCR/files/7746169/error.log)
系统：Win10
Python 环境：virtualenv + python3.7.9
![image](https://user-images.githubusercontent.com/28062894/146788455-b1c28dc9-c318-40f2-b6a6-2a02227df023.png)

**Comment by lewangdev** [comment]
windows 下是需要安装这些工具的，根据日志中错误提示安装对应的依赖，默认勾选就行


```
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
```

![image](https://user-images.githubusercontent.com/1455685/146874657-a3f3fce7-7d49-4d6a-9f9c-f60271a752b5.png)

![image](https://user-images.githubusercontent.com/1455685/146874665-9e4e83e4-e458-4a4a-9389-f51a064f4c22.png)
